CREATE TABLE IF NOT EXISTS public.favorites (
  favorite_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id     integer NOT NULL,
  inv_id         integer NOT NULL,
  created_at     timestamp with time zone DEFAULT now(),
  CONSTRAINT fk_fav_account FOREIGN KEY (account_id) REFERENCES public.account(account_id) ON DELETE CASCADE,
  CONSTRAINT fk_fav_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
  CONSTRAINT unique_account_vehicle UNIQUE (account_id, inv_id)
);
